### ISSUE TITLE
PDF toolkit with Alfresco community 5.1

### ISSUE THREAD

**Issue by mdragatsis** [ntmcminn/alfresco-pdf-toolkit#22]
I have 5.1 community running on windows 2008 server. When I install the latest PDF toolkit and restart the alfresco server, I can not log in. Does anyone know if 5.1 community works with PDF toolkit?

**Comment by ntmcminn** [comment]
Totally untested with 5.1.  That's next on my list.  I'll leave this issue open to track progress.

**Comment by ntmcminn** [comment]
1.4.0 is posted as a release, and had been tested with 5.1.e.  Please give it a try and let me know if it resolves your issue.

**Comment by robsoncardosoti** [comment]
Where i find the amp file?

**Comment by mdragatsis** [comment]
Yes, where can we download the AMP files?

**Comment by mdragatsis** [comment]
here they are 

https://github.com/ntmcminn/alfresco-pdf-toolkit/releases

**Comment by amet123** [comment]
after install fresh Community 5.1 version in window 

But Still same issue  **

> An error occurred when the form was about to be displayed

**

**Comment by chromaphase75** [comment]
Having the same issue after installing version 1.4. The form error is returning when attempting to use any of the available functions on a PDF doc.

I'm running a Alfresco One 5.1 / Ubuntu 16.04 environment.

**Comment by avmcf** [comment]
I install the CE 5.1 in Mac OS X (10.11.6) and all was OK, but when I try create a rule for split a PDF on the option for "destination folder" does not appear the button to choose destination folder like the youtube teaser (http://www.youtube.com/watch?v=cJYpFgx037E)

**Comment by oodalis** [comment]
I have the same issue as AVMCF i am unable to set destination folder when i am trying to make a rule on a folder , please i will like to use this excellent product , i really need some help on this.
Thanks.

**Comment by avmcf** [comment]
MAC_OS 10.11.6 / Alfresco CE 5.1 / SDK 2.2

Unfortunately when a try to build the AMPs file through the command: mvn clean install -Prun the following error occurs:

________________________________________________________________________________________________________
GRAVE: Exception starting filter X509AuthFilter
javax.servlet.ServletException: java.lang.NullPointerException
	at org.alfresco.web.scripts.servlet.X509ServletFilterBase.init(X509ServletFilterBase.java:103)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4775)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5452)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.alfresco.solr.servlet.Solr4X509ServletFilter.findCores(Solr4X509ServletFilter.java:133)
	at org.alfresco.solr.servlet.Solr4X509ServletFilter.checkEnforce(Solr4X509ServletFilter.java:72)
	at org.alfresco.web.scripts.servlet.X509ServletFilterBase.init(X509ServletFilterBase.java:73)
	... 12 more

 2016-08-29 14:52:31,435  ERROR [solr.core.CoreContainer] [coreLoadExecutor-5-thread-1] Error creating core [collection1]: Could not load conf for core collection1: Error loading solr config from /Users/avmcf/maven_projects/alfresco-pdf-toolkit-1.4.0/alf_data_dev/solr4/config/collection1/conf/solrconfig.xml
 org.apache.solr.common.SolrException: Could not load conf for core collection1: Error loading solr config from /Users/avmcf/maven_projects/alfresco-pdf-toolkit-1.4.0/alf_data_dev/solr4/config/collection1/conf/solrconfig.xml
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:66)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:489)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:255)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:249)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Error loading solr config from /Users/avmcf/maven_projects/alfresco-pdf-toolkit-1.4.0/alf_data_dev/solr4/config/collection1/conf/solrconfig.xml
	at org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:154)
	at org.apache.solr.core.ConfigSetService.createSolrConfig(ConfigSetService.java:80)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:61)
	... 7 more
Caused by: java.io.IOException: Can't find resource 'solrconfig.xml' in classpath or '/Users/avmcf/maven_projects/alfresco-pdf-toolkit-1.4.0/alf_data_dev/solr4/config/collection1/conf'
	at org.apache.solr.core.SolrResourceLoader.openResource(SolrResourceLoader.java:362)
	at org.apache.solr.core.SolrResourceLoader.openConfig(SolrResourceLoader.java:308)
	at org.apache.solr.core.Config.<init>(Config.java:117)
	at org.apache.solr.core.Config.<init>(Config.java:87)
	at org.apache.solr.core.SolrConfig.<init>(SolrConfig.java:167)
	at org.apache.solr.core.SolrConfig.readFromResourceLoader(SolrConfig.java:145)
	... 9 more
ago 29, 2016 2:52:31 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Error filterStart
ago 29, 2016 2:52:31 PM org.apache.catalina.core.StandardContext startInternal
GRAVE: Context [/solr4] startup failed due to previous errors
ago 29, 2016 2:52:31 PM org.apache.coyote.AbstractProtocol start
INFORMAÇÕES: Starting ProtocolHandler ["http-bio-8080"]

**Comment by douglascrp** [comment]
As I can not reproduce the error with the current version, is it ok to close it?

**Comment by amar7295** [comment]
Hi everyone,

I have installed amp files and checked with files this works properly except the "Insert into PDF".It says "Insert Operation Failed"

so can you help me with this?

thanks and regards.
