### ISSUE TITLE
Error SEVERE: Exception starting filter X509AuthFilter

### ISSUE THREAD

**Issue by adayanecoutinho** [ntmcminn/alfresco-pdf-toolkit#52]
As I try to compile version 1.4.0 this error happens.

Oct 16, 2018 12:19:40 PM org.apache.catalina.core.StandardContext filterStart
SEVERE: Exception starting filter X509AuthFilter
javax.servlet.ServletException: java.lang.NullPointerException
        at org.alfresco.web.scripts.servlet.X509ServletFilterBase.init(X509ServletFilterBase.java:103)
        at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
        at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
        at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
        at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4775)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5452)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at org.alfresco.solr.servlet.Solr4X509ServletFilter.findCores(Solr4X509ServletFilter.java:133)
        at org.alfresco.solr.servlet.Solr4X509ServletFilter.checkEnforce(Solr4X509ServletFilter.java:72)
        at org.alfresco.web.scripts.servlet.X509ServletFilterBase.init(X509ServletFilterBase.java:73)
        ... 12 more

**Comment by douglascrp** [comment]
Why are you trying to compile the version 1.4.0 when there is already a new version available, which is the 1.4.2?
Have you tried to compile it?
What command are you using? And from what folder are you running it?

**Comment by adayanecoutinho** [comment]
In version 1.4.2 I also had errors, then I decided to try version 1.4.0. I am compiling on a linux centos 7 server, I just run the run.sh script.

**Comment by douglascrp** [comment]
In order to "compile/package" the project, run "mvn install" instead
The AMP files will be generated inside the target folder

**Comment by adayanecoutinho** [comment]
Running the run.sh script from pdftoolkit 1.4.2 it does not show error, but finishes executing with the message:
2018-10-16 16: 19: 37,032 INFO [solr.component.AsyncBuildSuggestComponent] [Suggestor-alfresco-1] Loaded suggester shingleBasedSuggestions, took 718 ms

is correct?

**Comment by adayanecoutinho** [comment]
I was able to compile, installed on alfresco but only the options appear when creating folder rules. Is there anything to do?

**Comment by douglascrp** [comment]
@adayanecoutinho The actions will appear automatically inside the document libraries for PDF documents.
If that is not the case, so you have something wrong with your setup.
Can you share the versions for alfresco, share, and the addon.
Share the file names too (just to make sure you are using the right files) and the method you used to install it?

I am using it without any problem.
