### ISSUE TITLE
Error on Alfresco 6.0

### ISSUE THREAD

**Issue by renatofritola** [ntmcminn/alfresco-pdf-toolkit#53]
When I try to install pdf addon toolkit alfresco generates the following error:

```java
at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1301),
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patch.updateAdminUserWhenDefault' defined in URL [jar:file:/usr/local/tomcat/webapps/alfresco/WEB-INF/lib/alfresco-repository-7.22.jar!/alfresco/patch/patch-services-context.xml]: Invocation of init method failed; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.alfresco.web.app.ResourceBundleBootstrap] for bean with name 'bootstrapExtraBundlesBean' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/org.alfresco.extension.pdftoolkit/module-context.xml]; nested exception is java.lang.ClassNotFoundException: org.alfresco.web.app.ResourceBundleBootstrap,
2018-10-29 19:37:15,941 ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed,
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498),
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199),
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1745),
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576),
at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320),
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222),
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318),
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846),
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511),
at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1875),
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:726),
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863),
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546),
at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400),
at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291),
at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103),
at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70),
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4753),
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5215),
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150),
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752),
at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129),
at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:150),
at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:140),
at java.security.AccessController.doPrivileged(Native Method),
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734),
at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1141),
at java.util.concurrent.FutureTask.run(FutureTask.java:266),
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149),
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624),
at java.lang.Thread.run(Thread.java:748),
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.alfresco.web.app.ResourceBundleBootstrap] for bean with name 'bootstrapExtraBundlesBean' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/org.alfresco.extension.pdftoolkit/module-context.xml]; nested exception is java.lang.ClassNotFoundException: org.alfresco.web.app.ResourceBundleBootstrap,
at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1379),
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:663),
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:630), 
... 30 more,
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1741),
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1794),
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$invokeInitMethods$5(AbstractAutowireCapableBeanFactory.java:1795),
at org.alfresco.repo.admin.patch.impl.AdminUserPatch.afterPropertiesSet(AdminUserPatch.java:117),
at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1101),
at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341),
at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:335),
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:413),
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1098),
at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:462),
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:407),
at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:485),
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:507),
at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1491)
```

**Comment by douglascrp** [comment]
@renatofritola The pending PR got merged. Please, give it a try.

**Comment by jrbrasil** [comment]
@douglascrp Do you have the updated Pdf took kit for version 6.1.1 of Alfresco?
Has the amps?
Thanks a lot.

**Comment by douglascrp** [comment]
Hey.

You can clone the project into your computer, and then, inside of the modules folders' (pdf-toolkit-repo and pdf-toolkit-share), execute mvn clean install

Once finished, you will have the amp files into the target folders.

**Comment by jrbrasil** [comment]
Hi douglascrp,
I did it, but an error occurs.
Look:

root @ servertwtech: ~ / install / alfresco-pdf-toolkit # mvn clean install
[INFO] Scanning for projects ...
[INFO] ----------------------------------------------- -------------------------
[INFO] BUILD FAILURE
[INFO] ----------------------------------------------- -------------------------
[INFO] Total time: 0.190 s
[INFO] Finished at: 2020-01-30T08: 51: 47-03: 00
[INFO] ----------------------------------------------- -------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/ root / install / alfresco-pdf-toolkit). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

Do you have the generated amps from pdf-took-kit in version 6.1?
If so, could you make it available?
Thank you.
hug

**Comment by douglascrp** [comment]
You have to run that inside of the two folders, pdf-toolkit-repo and pdf-toolkit-share, not in the root folder.
Do that and you will have the amp files.

**Comment by jrbrasil** [comment]
Hi douglascrp,
I ran the mvc clean install command in each folder.
He generated the amps

-rw-r - r-- 1 root 2.2M Jan 31 10:14 pdf-toolkit-repo-1.4.4-SNAPSHOT.amp
-rw-r - r-- 1 root 35K Jan 31 10:16 pdf-toolkit-share-1.4.3-SNAPSHOT.amp

However, an error is occurring when using the functions of the pdf tool kit
Error message:

An error occurred when the form was about to be displayed

Error in catalina.out
root @ servertwtech: ~ # tail -f /opt/alfresco/tomcat/logs/catalina.out

  2020-01-31 11: 08: 51,889 ERROR [scripts.forms.FormUIGet] [http-nio-8080-exec-18] org.alfresco.repo.forms.FormException: 00310001 Failed to find appropriate FormProcessor to generate Form for item : [pdf-action] pdf-insert-at-page

Any other tips, to work in version 6.1.1 of Alfresco?
Thanks.

**Comment by douglascrp** [comment]
Where did you put the amp files?
What commands have you executed to install them?

Just to make sure you have installed them correctly, the pdf-toolkit-repo-1.4.4-SNAPSHOT.amp should be in the amps folder, and the pdf-toolkit-share-1.4.3-SNAPSHOT.amp file in the amps_share folder (considering that you are using the folders structured created by the installer)

**Comment by jrbrasil** [comment]
Hi douglascrp,

I placed the amps files, in the following structure:
/opt/alfresco/addons/share/
pdf-toolkit-repo-1.4.4-SNAPSHOT.amp
pdf-toolkit-share-1.4.3-SNAPSHOT.amp

/opt/alfresco/addons
pdf-toolkit-repo-1.4.4-SNAPSHOT.amp
pdf-toolkit-share-1.4.3-SNAPSHOT.amp

In version 6.1.1 installed with alfinstall.sh script it does not have the amps directory.
Did I put the amps files in the correct location?

I ran the command as follows:

/opt/alfresco/addons/apply.sh amp pdf-toolkit-repo-1.4.4-SNAPSHOT.amp pdf-toolkit-share-1.4.3-SNAPSHOT.amp -force

Then copy share.war to the directory /opt/alfresco/tomcat/webapps/

Is the procedure correct?
With best regards,
